name: "Auto PR Reviewer"
description: "Automatically reviews PRs using Gemini"
author: "Keshav Gilhotra"

inputs:
  GEMINI_API_KEY:
    description: "GEMINI API key"
    required: true

runs:
  using: "node16"
  main: "index.js"